openapi: 3.0.3
info:
  title: DateCourses API
  version: 0.1.1
servers:
  - description: Development server
    url: http://localhost:7777
  - description: Production server
    url: https://api.datecourses.com
tags:
  - name: top
    description: Information about the top-level API features
  - name: session
    description: Details about user sessions and authentication
  - name: user
    description: Information related to user profiles and data
  - name: date_spot
    description: Details about various date spots available
  - name: date_spot_review
    description: User reviews and ratings for date spots
  - name: course
    description: Information about different date courses offered
  - name: prefecture
    description: Details about prefectures and their locations
  - name: genre
    description: Information about different genres of date spots
paths:
  /:
    get:
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "./components/schemas/response/default.yaml#/components/schemas/WelcomeResponseData"
  /api/v1/top:
    get:
      tags: ["top"]
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "./components/schemas/response/default.yaml#/components/schemas/TopResponseData"
  /api/v1/signup:
    post:
      tags: ["session"]
      requestBody:
        required: true
        content:
          multipart/form-data:
              schema:
                $ref: './components/schemas/request/registration.yaml#/components/schemas/SignupFormData'
      responses:
        "201":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: './components/schemas/response/registration.yaml#/components/schemas/SignUpResponseData'
  # /api/v1/login:
    # post:
    #   tags: ["session"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  /api/v1/users:
    get:
      tags: ["user"]
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/response/user.yaml#/components/schemas/UserResponseData"
  /api/v1/users/{id}:
    get:
      tags: ["user"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "./components/schemas/response/user.yaml#/components/schemas/UserResponseData"
    # put:
    #   tags: ["user"]
    #   responses:
    #     "200":
    #       description: "Successful response"
    # delete:
    #   tags: ["user"]
    #   responses:
    #     "204":
    #       description: "Successful response"
  # /api/v1/user_name_search:
    # post:
    #   tags: ["user"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  /api/v1/users/{user_id}/followings:
      get:
        tags: ["user"]
        parameters:
          - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/UserIdParam"
        responses:
          "200":
            description: "Successful response"
            content:
              application/json:
                schema:
                  $ref: "./components/schemas/response/relationship.yaml#/components/schemas/RelationShipResponsData"
  /api/v1/users/{user_id}/followers:
    get:
      tags: ["user"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/UserIdParam"
      responses:
        "200":
          description: "Successful response"
          content:
              application/json:
                schema:
                  $ref: "./components/schemas/response/relationship.yaml#/components/schemas/RelationShipResponsData"

  # /api/v1/relationships:
    # post:
    #   tags: ["user"]
    #   responses:
    #     "201":
    #       description: "Successful response"
  # /api/v1/relationships/{current_user_id}/{other_user_id}:
  #   delete:
  #     tags: ["user"]
  #     parameters:
  #       - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/CurrentUserIdParam"
  #       - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/OtherUserIdParam"
  #     responses:
  #       "200":
  #         description: "Successful response"
  # /api/v1/date_spot_name_search:
    # post:
    #   tags: ["date_spot"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  # /api/v1/date_spots/sort:
    # post:
    #   tags: ["date_spot"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  # /api/v1/courses/sort:
    # post:
    #   tags: ["course"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  /api/v1/date_spots:
    get:
      tags: ["date_spot"]
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/response/address_and_date_spot.yaml#/components/schemas/AddressAndDateSpotsData"
    # post:
    #   tags: ["date_spot"]
    #   responses:
    #     "201":
    #       description: "Successful response"
  /api/v1/date_spots/{id}:
    get:
      tags: ["date_spot"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "./components/schemas/response/address_and_date_spot.yaml#/components/schemas/AddressAndDateSpotsData"
    # put:
    #   tags: ["date_spot"]
    #   responses:
    #     "200":
    #       description: "Successful response"
    # delete:
    #   tags: ["date_spot"]
    #   responses:
    #     "204":
    #       description: "Successful response"
  # /api/v1/date_spot_reviews:
    # post:
    #   tags: ["date_spot_review"]
    #   responses:
    #     "201":
    #       description: "Successful response"
  # /api/v1/date_spot_reviews/{id}:
    # put:
    #   tags: ["date_spot_review"]
    #   parameters:
    #      - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
    #   responses:
    #     "200":
    #       description: "Successful response"
    # delete:
    #   tags: ["date_spot_review"]
    #   responses:
    #     "200":
    #       description: "Successful response"
  /api/v1/prefectures/{id}:
    get:
      tags: ["prefecture"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/response/address_and_date_spot.yaml#/components/schemas/AddressAndDateSpotsData"
  /api/v1/genres/{id}:
    get:
      tags: ["genre"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
      responses:
        "200":
          description: "Successful response"
  /api/v1/courses:
    get:
      tags: ["course"]
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "./components/schemas/response/course.yaml#/components/schemas/CourseResponseData"
    # post:
    #   tags: ["course"]
    #   responses:
    #     "201":
    #       description: "Successful response"
  /api/v1/courses/{id}:
    get:
      tags: ["course"]
      parameters:
        - $ref: "./components/schemas/response/parameter.yaml#/components/parameters/IdParam"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/schemas/response/course.yaml#/components/schemas/CourseResponseData"

    # delete:
    #   tags: ["course"]
    #   responses:
    #     "204":
    #       description: "Successful response"

